### ISSUE TITLE
Alignment problem:Manage Templates-The details of "date & time" under  "Edited at" ist not properly aligned

### ISSUE THREAD

**Issue by sbalachander1** [wte4j/wte4j#37]
1.In "showcase"click on "Manage Templates"
2..The date and time which are displayed under "Edited at" are not properly aligned

Please see screnshot

P.S 1:All other columns are aligned in the left,whereas the details of "Edited at" are aligned towards tthe right
![23-06-2015 08-47-44](https://cloud.githubusercontent.com/assets/13013603/8306245/e4552e40-19b6-11e5-8afe-d1a50bcef41a.png)

**Comment by selbert** [comment]
fixed in #47
