### ISSUE TITLE
Content Control Tag-There are 2 entries of First & Last name,whereas the dropdown has only one entry of First und Last name!

### ISSUE THREAD

**Issue by sbalachander1** [wte4j/wte4j#38]
1.¨Click on "Create new Template from file" 
2.A table "Create New Template" will appear.Under "Available Data Models",there is a descripstion as "org.wte4j.examples.showcase.shared.OrderDataDto".
a.What does that mean?
b.We can click on it,but "NOTHING HAPPENS" !!
(PLEASE SEE SCREENSHOT 1)
3.Click on "Submit" 
4.a table "Create new Template" appears.
5.Under "Content control Tag Name"  the "First & Last Name" appears twice,but in Dropdown,we can see the first name and last name only once
6.for which First name and last name from MS-Word corresponds,the first name and last name from Drop down of  "Content Control Tag" ?
(PLEASE SEE SCREENSHOT 2 )
This issue is already with Tom on 23.06.15 discussed,
The 2nd entry of "First name " and "Last name" should either be deleted from drop down or should be clearly mentioned,which name corresponds to which name in Word document.

![24-06-2015 09-02-52](https://cloud.githubusercontent.com/assets/13013603/8349386/893cbd18-1b1c-11e5-8d20-303536d06da0.png)
![24-06-2015 09-08-11](https://cloud.githubusercontent.com/assets/13013603/8349387/8942d54a-1b1c-11e5-847b-b01f3bfdd796.png)

**Comment by ofreivogel** [comment]
When two content control elements have the same tag value, they get the same value from the data inserted, when a document will be generated. Therefor in the Mapping table the id is shown only once.
