### ISSUE TITLE
Content control Tags to Model Key mapping

### ISSUE THREAD

**Issue by selbert** [wte4j/wte4j#51]
Should it really be possible to map content control tags with the same name to different model key?
![cct_to_multiple_modelkeys](https://cloud.githubusercontent.com/assets/2499754/9217553/3c4037ba-40c9-11e5-9da1-c0e389359f65.PNG)

**Comment by ofreivogel** [comment]
No it should not. Name of Tags shoud be unique. We need a validation there.
